---
- name: Redmine
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  vars_prompt:
    - name: 'redmine_language_number'
      prompt: "\nPlease choose the number for Redmine language [ 1/2] \n
      1: English\n
      2: Chinese\n"
      private: no
      default: 1
  
  vars:
    temp_ver:
      '1': 'en'
      '2': 'zh'
    redmine_lang: "{{temp_ver[redmine_language_number]}}" 

  vars_files: 
    - vars/main.yml

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_ruby, tags: "role_ruby"}
    - {role: role_nginx, tags: "role_nginx"}
    - {role: role_mysql, tags: "role_mysql"}
    - {role: redmine, tags: "redmine"}      
    - {role: role_docker, tags: "role_docker"}
    - {role: role_init, tags: "role_init"}
    - {role: role_preend, tags: "role_preend"} 
    - {role: role_end, tags: "role_end"}   
